# Generated by Django 4.2.13 on 2025-08-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='statusupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='statusupdate',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
